substitutions:
  status_led_brightness: 20%

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    disabled_by_default: true
    pin: GPIO38
    num_leds: 1
    chipset: ws2812
    rgb_order: RGB
    default_transition_length: 0s
    restore_mode: ALWAYS_OFF
    icon: "mdi:led-variant-on"

script:
  - id: update_status_led
    mode: restart
    parameters:
      boot_stage: int
    then:
      - light.turn_on:
          id: status_led
          brightness: ${status_led_brightness}
          red: !lambda 'return boot_stage == 3 ? 0.0f : 1.0f;'
          green: !lambda 'return boot_stage == 1 ? 0.0f : (boot_stage == 2 ? 0.6f : 1.0f);'
          blue: 0%

esphome:
  on_boot:
    - priority: 798 # HARDWARE - 2
      then:
        - script.execute:
            id: update_status_led
            boot_stage: 1

    - priority: -10000 # LATE * 100
      then:
        - script.execute:
            id: update_status_led
            boot_stage: 2

wifi:
  on_connect:
    - script.execute:
        id: update_status_led
        boot_stage: 3
  on_disconnect:
    - script.execute:
        id: update_status_led
        boot_stage: 2
